### ISSUE TITLE
Polygon ring order

### ISSUE THREAD

**Issue by nryeng** [awesome-raccoons/gqt#15]
Currently, inner rings must be in the opposite direction of the outer ring. Any ring order should be accepted.

One example of a ring order flipping algorithm:
https://github.com/mysql/mysql-server/blob/5.7/sql/spatial.cc#L2002

**Comment by EirikUlversoy** [comment]
This should be fixed now, have tested with some polygons that worked incorrectly before.

Holes that are inside of other holes still show incorrectly, I think it is due to the outer ring now being another hole instead of the main outer ring. Is this something that needs to work?

**Comment by nryeng** [comment]
Overlapping holes are invalid, so it's not strange that they're hard to plot. I think we can live with that, at least for now.
