### ISSUE TITLE
Show/edit WKT for each layer

### ISSUE THREAD

**Issue by nryeng** [awesome-raccoons/gqt#18]
There is currently no way to inspect the WKT of a layer after it has been created. The WKT textbox should be updated to always reflect the current layer, and it should be possible to edit the WKT and redraw the layer.

**Comment by johannbm** [comment]
I have a couple of questions about the abillity to redraw the layer after changing its WKT string.

A: What I originally thought we would do:
1. you select a layer.
2. the text area displays the WKT string used to draw this layer
3. you edit the WKT and press submit
4. there is now a new modified layer, in addition to the ones you already had.
(5.) eventually you could delete the old one, and hence have "redrawn" it.

B: How I assume you want it to work:
1. select a layer
2. text area displays the WKT string used to draw this layer
3. edit it and press submit
4. the same layer now represents a new geometry

I think this could eventually become inconvinient. For example, I think it would be quite easy to forget to unselect layers. Say you actually wanted to draw some new WKT on a new layer, but you forgot to unselect all layers, so now you have instead overwritten it.

What I am suggesting (you're the boss, you choose):
When you select a layer, the WKT string pops up in the WKT input area, but it follows the procedure outline in A.
But when you double click a layer, you open a new window with more detailed information about the layer where you can:
- see current color
- select new color and opacity
- edit name
- Field for showing WKT string that can be edited
- Button for redrawin the layer and saving changes.

What do you think?

**Comment by nryeng** [comment]
@johannbm I like the B use case.

To get a new, empty layer, a "New layer" button will do. Since new layers have empty WKT boxes, there will be no confusion about whether the user is adding a new layer or editing an existing one.

But you raise an interesting point about what to do when selecting multiple layers. Unless you have other ideas, I suggest you just disable the input boxes if multiple layers are selected. It doesn't make sense to edit the SQL or WKT of several layers at the same time.
