### ISSUE TITLE
Geometry collections should be one layer

### ISSUE THREAD

**Issue by nryeng** [awesome-raccoons/gqt#19]
Geometry collections (and subclasses multipoint, multilinestring and multipolygon) should be displayed as one layer. It's useful to split them up into their components, but it must be possible to treat the whole collection as one layer.

A tree structure would be nice. Note that geometry collections may contain several levels of nested collections.

**Comment by johannbm** [comment]
How important would you label the feature to implement a tree structure, opposed to just drawing geometrycollections on one layer?

**Comment by johannbm** [comment]
Right now I can think of a lot of challenges that will come with implementing a tree structure, especially now that you can edit a layer and make it update its drawing. Things would quickly get complicated as opposed to just drawing everything on one layer. Just wanted to specify and know how you view this tradeoff.

**Comment by nryeng** [comment]
Drawing collections on one layer is the important part. A tree structure would be nice, but it has a low priority.

**Comment by johannbm** [comment]
Right now I've implemented the drawing of collections to one layer. Right now we assign a preset color to each layer, so they all get the same color and it may be difficult to see the different components within the collections. Should each component in a collection have a different color, or do you prefer the color assigned to a layer to apply to all components?

**Comment by nryeng** [comment]
One color for the whole layer.
