### ISSUE TITLE
Layers change name when the WKT is changed

### ISSUE THREAD

**Issue by nryeng** [awesome-raccoons/gqt#41]
When the WKT for a layer is edited, the name of the layer is changed. The name should never change.

To reproduce:
- Create a layer, enter POINT(0 0) and press submit.
- Rename the layer to "a".
- Edit the WKT for that layer, change it to POINT(1 1) and press submit.

**Comment by johannbm** [comment]
I will just close the issues we think are fixed. If you still find some bugs, just reopen them.
